apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster42
  region: ap-northeast-2
  version: "1.28"


iam:
  withOIDC: true

vpc:
  id: "vpc-0a014f7e7ac68f1b0"
  # cidr: "192.168.0.0/16"
  subnets:
    public:
      public-a:
          id: "subnet-02eab2b6bd3878993"
          # cidr: "192.168.0.0/19"
      public-b:
          id: "subnet-05777fe1d871d16d9"
          # cidr: "192.168.64.0/19"
    private:
      private-a:
          id: "subnet-0bbf99c5227e5d9f9"
          # cidr: "192.168.32.0/19"
      private-b:
          id: "subnet-0636266062362af9b"
          # cidr: "192.168.96.0/19"



nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    # minCapacity: 1
    # maxCapacity: 3
    subnets:
      - public-a
      - public-b
    # subnets: ["subnet-02eab2b6bd3878993", "subnet-05777fe1d871d16d9"]
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 2
    subnets:
      - private-a
    privateNetworking: true


cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

    # Sets the number of days to retain the logs for (see [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax)).
    # By default, log data is stored in CloudWatch Logs indefinitely.
    logRetentionInDays: 30


addons:
- name: vpc-cni # no version is specified so it deploys the default version
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  wellKnownPolicies:      # add IAM and service account
    ebsCSIController: true